site_name: 'Research Repository Documentation'

repo_url: https://github.com/r4ppz/research-repo-docs

theme:
    name: material
    icon:
        logo: material/book-open-variant
    language: en

    palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: sky blue
          accent: sky blue
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: sky blue
          accent: sky blue
          toggle:
              icon: material/weather-night
              name: Switch to light mode
          icon:
              repo: fontawesome/brands/github

    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.copy

extra:
    generator: false

nav:
    - Home: index.md
    - Specification: specification.md
    - API Contract: api_contract.md
    - API Contract (Improved): rest_api.md
    - Database: database_migration.md
    - Testing: testing.md

extra_javascript:
    - js/open_in_new_tab.js

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
